let data =
[
  {
    "state": "Alaska",
    "code": "AK",
    "row": 1,
    "col": 1,
    "rank": 36,
    "installed_capacity_mw": 62,
    "equivalent_homes_powered": 15200,
    "total_investment_mn": 126,
    "wind_projects_online": 19,
    "wind_turbines": 104
  },
  {
    "state": "Maine",
    "code": "ME",
    "row": 1,
    "col": 11,
    "rank": 22,
    "installed_capacity_mw": 923,
    "equivalent_homes_powered": 206500,
    "total_investment_mn": 1800,
    "wind_projects_online": 18,
    "wind_turbines": 386
  },
  {
    "state": "Wisconsin",
    "code": "WI",
    "row": 2,
    "col": 6,
    "rank": 23,
    "installed_capacity_mw": 746,
    "equivalent_homes_powered": 142100,
    "total_investment_mn": 1500,
    "wind_projects_online": 18,
    "wind_turbines": 466
  },
  {
    "state": "Vermont",
    "code": "VT",
    "row": 2,
    "col": 10,
    "rank": 34,
    "installed_capacity_mw": 149,
    "equivalent_homes_powered": 25900,
    "total_investment_mn": 300,
    "wind_projects_online": 9,
    "wind_turbines": 71
  },
  {
    "state": "New Hampshire",
    "code": "NH",
    "row": 2,
    "col": 11,
    "rank": 32,
    "installed_capacity_mw": 185,
    "equivalent_homes_powered": 38500,
    "total_investment_mn": 374,
    "wind_projects_online": 5,
    "wind_turbines": 75
  },
  {
    "state": "Washington",
    "code": "WA",
    "row": 3,
    "col": 1,
    "rank": 10,
    "installed_capacity_mw": 3075,
    "equivalent_homes_powered": 695300,
    "total_investment_mn": 6100,
    "wind_projects_online": 20,
    "wind_turbines": 1725
  },
  {
    "state": "Idaho",
    "code": "ID",
    "row": 3,
    "col": 2,
    "rank": 20,
    "installed_capacity_mw": 973,
    "equivalent_homes_powered": 228000,
    "total_investment_mn": 2100,
    "wind_projects_online": 15,
    "wind_turbines": 541
  },
  {
    "state": "Montana",
    "code": "MT",
    "row": 3,
    "col": 3,
    "rank": 24,
    "installed_capacity_mw": 720,
    "equivalent_homes_powered": 199800,
    "total_investment_mn": 1400,
    "wind_projects_online": 16,
    "wind_turbines": 493
  },
  {
    "state": "North Dakota",
    "code": "ND",
    "row": 3,
    "col": 4,
    "rank": 11,
    "installed_capacity_mw": 2996,
    "equivalent_homes_powered": 1021000,
    "total_investment_mn": 5800,
    "wind_projects_online": 28,
    "wind_turbines": 1611
  },
  {
    "state": "Minnesota",
    "code": "MN",
    "row": 3,
    "col": 5,
    "rank": 7,
    "installed_capacity_mw": 3699,
    "equivalent_homes_powered": 1012000,
    "total_investment_mn": 7100,
    "wind_projects_online": 98,
    "wind_turbines": 2428
  },
  {
    "state": "Illinois",
    "code": "IL",
    "row": 3,
    "col": 6,
    "rank": 6,
    "installed_capacity_mw": 4464,
    "equivalent_homes_powered": 1050000,
    "total_investment_mn": 8900,
    "wind_projects_online": 49,
    "wind_turbines": 2632
  },
  {
    "state": "Michigan",
    "code": "MI",
    "row": 3,
    "col": 7,
    "rank": 13,
    "installed_capacity_mw": 1904,
    "equivalent_homes_powered": 471700,
    "total_investment_mn": 3500,
    "wind_projects_online": 26,
    "wind_turbines": 1051
  },
  {
    "state": "New York",
    "code": "NY",
    "row": 3,
    "col": 9,
    "rank": 14,
    "installed_capacity_mw": 1829,
    "equivalent_homes_powered": 366500,
    "total_investment_mn": 3700,
    "wind_projects_online": 27,
    "wind_turbines": 1052
  },
  {
    "state": "Massachusetts",
    "code": "MA",
    "row": 3,
    "col": 10,
    "rank": 35,
    "installed_capacity_mw": 113,
    "equivalent_homes_powered": 20500,
    "total_investment_mn": 236,
    "wind_projects_online": 44,
    "wind_turbines": 86
  },
  {
    "state": "Oregon",
    "code": "OR",
    "row": 4,
    "col": 1,
    "rank": 8,
    "installed_capacity_mw": 3213,
    "equivalent_homes_powered": 604600,
    "total_investment_mn": 6600,
    "wind_projects_online": 31,
    "wind_turbines": 1868
  },
  {
    "state": "Nevada",
    "code": "NV",
    "row": 4,
    "col": 2,
    "rank": 33,
    "installed_capacity_mw": 152,
    "equivalent_homes_powered": 33600,
    "total_investment_mn": 306,
    "wind_projects_online": 1,
    "wind_turbines": 66
  },
  {
    "state": "Wyoming",
    "code": "WY",
    "row": 4,
    "col": 3,
    "rank": 16,
    "installed_capacity_mw": 1489,
    "equivalent_homes_powered": 408700,
    "total_investment_mn": 3100,
    "wind_projects_online": 22,
    "wind_turbines": 1005
  },
  {
    "state": "South Dakota",
    "code": "SD",
    "row": 4,
    "col": 4,
    "rank": 19,
    "installed_capacity_mw": 977,
    "equivalent_homes_powered": 293100,
    "total_investment_mn": 2100,
    "wind_projects_online": 14,
    "wind_turbines": 583
  },
  {
    "state": "Iowa",
    "code": "IA",
    "row": 4,
    "col": 5,
    "rank": 3,
    "installed_capacity_mw": 7312,
    "equivalent_homes_powered": 1935000,
    "total_investment_mn": 14200,
    "wind_projects_online": 107,
    "wind_turbines": 4145
  },
  {
    "state": "Indiana",
    "code": "IN",
    "row": 4,
    "col": 6,
    "rank": 12,
    "installed_capacity_mw": 2117,
    "equivalent_homes_powered": 440700,
    "total_investment_mn": 4500,
    "wind_projects_online": 16,
    "wind_turbines": 1203
  },
  {
    "state": "Ohio",
    "code": "OH",
    "row": 4,
    "col": 7,
    "rank": 26,
    "installed_capacity_mw": 617,
    "equivalent_homes_powered": 145300,
    "total_investment_mn": 1200,
    "wind_projects_online": 37,
    "wind_turbines": 336
  },
  {
    "state": "Pennsylvania",
    "code": "PA",
    "row": 4,
    "col": 8,
    "rank": 18,
    "installed_capacity_mw": 1369,
    "equivalent_homes_powered": 314000,
    "total_investment_mn": 2800,
    "wind_projects_online": 24,
    "wind_turbines": 726
  },
  {
    "state": "New Jersey",
    "code": "NJ",
    "row": 4,
    "col": 9,
    "rank": 39,
    "installed_capacity_mw": 9,
    "equivalent_homes_powered": 1900,
    "total_investment_mn": 15,
    "wind_projects_online": 2,
    "wind_turbines": 6
  },
  {
    "state": "Connecticut",
    "code": "CT",
    "row": 4,
    "col": 10,
    "rank": 40,
    "installed_capacity_mw": 5,
    "equivalent_homes_powered": 1300,
    "total_investment_mn": 9,
    "wind_projects_online": 2,
    "wind_turbines": 3
  },
  {
    "state": "Rhode Island",
    "code": "RI",
    "row": 4,
    "col": 11,
    "rank": 37,
    "installed_capacity_mw": 54,
    "equivalent_homes_powered": 14200,
    "total_investment_mn": 346,
    "wind_projects_online": 15,
    "wind_turbines": 25
  },
  {
    "state": "California",
    "code": "CA",
    "row": 5,
    "col": 1,
    "rank": 4,
    "installed_capacity_mw": 5686,
    "equivalent_homes_powered": 1298000,
    "total_investment_mn": 12600,
    "wind_projects_online": 104,
    "wind_turbines": 6972
  },
  {
    "state": "Utah",
    "code": "UT",
    "row": 5,
    "col": 2,
    "rank": 27,
    "installed_capacity_mw": 391,
    "equivalent_homes_powered": 86900,
    "total_investment_mn": 851,
    "wind_projects_online": 5,
    "wind_turbines": 205
  },
  {
    "state": "Colorado",
    "code": "CO",
    "row": 5,
    "col": 3,
    "rank": 9,
    "installed_capacity_mw": 3106,
    "equivalent_homes_powered": 889100,
    "total_investment_mn": 6000,
    "wind_projects_online": 25,
    "wind_turbines": 1949
  },
  {
    "state": "Nebraska",
    "code": "NE",
    "row": 5,
    "col": 4,
    "rank": 17,
    "installed_capacity_mw": 1445,
    "equivalent_homes_powered": 486700,
    "total_investment_mn": 2600,
    "wind_projects_online": 22,
    "wind_turbines": 789
  },
  {
    "state": "Missouri",
    "code": "MO",
    "row": 5,
    "col": 5,
    "rank": 21,
    "installed_capacity_mw": 959,
    "equivalent_homes_powered": 181100,
    "total_investment_mn": 1800,
    "wind_projects_online": 8,
    "wind_turbines": 499
  },
  {
    "state": "Kentucky",
    "code": "KY",
    "row": 5,
    "col": 6,
    "rank": "",
    "installed_capacity_mw": 0,
    "equivalent_homes_powered": "",
    "total_investment_mn": "",
    "wind_projects_online": 0,
    "wind_turbines": ""
  },
  {
    "state": "West Virginia",
    "code": "WV",
    "row": 5,
    "col": 7,
    "rank": 25,
    "installed_capacity_mw": 686,
    "equivalent_homes_powered": 149300,
    "total_investment_mn": 1400,
    "wind_projects_online": 6,
    "wind_turbines": 376
  },
  {
    "state": "Virginia",
    "code": "VA",
    "row": 5,
    "col": 8,
    "rank": "",
    "installed_capacity_mw": 0,
    "equivalent_homes_powered": "",
    "total_investment_mn": "",
    "wind_projects_online": 0,
    "wind_turbines": ""
  },
  {
    "state": "Maryland",
    "code": "MD",
    "row": 5,
    "col": 9,
    "rank": 31,
    "installed_capacity_mw": 191,
    "equivalent_homes_powered": 47500,
    "total_investment_mn": 397,
    "wind_projects_online": 6,
    "wind_turbines": 80
  },
  {
    "state": "Delaware",
    "code": "DE",
    "row": 5,
    "col": 10,
    "rank": 41,
    "installed_capacity_mw": 2,
    "equivalent_homes_powered": "",
    "total_investment_mn": 5,
    "wind_projects_online": 1,
    "wind_turbines": 1
  },
  {
    "state": "Arizona",
    "code": "AZ",
    "row": 6,
    "col": 2,
    "rank": 28,
    "installed_capacity_mw": 268,
    "equivalent_homes_powered": 54600,
    "total_investment_mn": 573,
    "wind_projects_online": 5,
    "wind_turbines": 144
  },
  {
    "state": "New Mexico",
    "code": "NM",
    "row": 6,
    "col": 3,
    "rank": 15,
    "installed_capacity_mw": 1682,
    "equivalent_homes_powered": 422100,
    "total_investment_mn": 2900,
    "wind_projects_online": 17,
    "wind_turbines": 1005
  },
  {
    "state": "Kansas",
    "code": "KS",
    "row": 6,
    "col": 4,
    "rank": 5,
    "installed_capacity_mw": 5110,
    "equivalent_homes_powered": 1719000,
    "total_investment_mn": 9400,
    "wind_projects_online": 35,
    "wind_turbines": 2795
  },
  {
    "state": "Arkansas",
    "code": "AR",
    "row": 6,
    "col": 5,
    "rank": "",
    "installed_capacity_mw": 0,
    "equivalent_homes_powered": "",
    "total_investment_mn": "",
    "wind_projects_online": 1,
    "wind_turbines": ""
  },
  {
    "state": "Tennessee",
    "code": "TN",
    "row": 6,
    "col": 6,
    "rank": 38,
    "installed_capacity_mw": 29,
    "equivalent_homes_powered": 2800,
    "total_investment_mn": 39,
    "wind_projects_online": 2,
    "wind_turbines": 18
  },
  {
    "state": "North Carolina",
    "code": "NC",
    "row": 6,
    "col": 7,
    "rank": 29,
    "installed_capacity_mw": 208,
    "equivalent_homes_powered": 43800,
    "total_investment_mn": 330,
    "wind_projects_online": 1,
    "wind_turbines": 105
  },
  {
    "state": "South Carolina",
    "code": "SC",
    "row": 6,
    "col": 8,
    "rank": "",
    "installed_capacity_mw": 0,
    "equivalent_homes_powered": "",
    "total_investment_mn": "",
    "wind_projects_online": 0,
    "wind_turbines": ""
  },
  {
    "state": "Oklahoma",
    "code": "OK",
    "row": 7,
    "col": 4,
    "rank": 2,
    "installed_capacity_mw": 7495,
    "equivalent_homes_powered": 2268000,
    "total_investment_mn": 13700,
    "wind_projects_online": 45,
    "wind_turbines": 3717
  },
  {
    "state": "Louisiana",
    "code": "LA",
    "row": 7,
    "col": 5,
    "rank": "",
    "installed_capacity_mw": 0,
    "equivalent_homes_powered": "",
    "total_investment_mn": "",
    "wind_projects_online": 0,
    "wind_turbines": ""
  },
  {
    "state": "Mississippi",
    "code": "MS",
    "row": 7,
    "col": 6,
    "rank": "",
    "installed_capacity_mw": 0,
    "equivalent_homes_powered": "",
    "total_investment_mn": "",
    "wind_projects_online": 0,
    "wind_turbines": ""
  },
  {
    "state": "Alabama",
    "code": "AL",
    "row": 7,
    "col": 7,
    "rank": "",
    "installed_capacity_mw": 0,
    "equivalent_homes_powered": "",
    "total_investment_mn": "",
    "wind_projects_online": 0,
    "wind_turbines": ""
  },
  {
    "state": "Georgia",
    "code": "GA",
    "row": 7,
    "col": 8,
    "rank": "",
    "installed_capacity_mw": 0,
    "equivalent_homes_powered": "",
    "total_investment_mn": "",
    "wind_projects_online": 0,
    "wind_turbines": ""
  },
  {
    "state": "Hawaii",
    "code": "HI",
    "row": 8,
    "col": 1,
    "rank": 30,
    "installed_capacity_mw": 206,
    "equivalent_homes_powered": 59800,
    "total_investment_mn": 412,
    "wind_projects_online": 7,
    "wind_turbines": 119
  },
  {
    "state": "Texas",
    "code": "TX",
    "row": 8,
    "col": 4,
    "rank": 1,
    "installed_capacity_mw": 23262,
    "equivalent_homes_powered": 6235000,
    "total_investment_mn": 42000,
    "wind_projects_online": 136,
    "wind_turbines": 12750
  },
  {
    "state": "Florida",
    "code": "FL",
    "row": 8,
    "col": 9,
    "rank": "",
    "installed_capacity_mw": 0,
    "equivalent_homes_powered": "",
    "total_investment_mn": "",
    "wind_projects_online": 0,
    "wind_turbines": ""
  }
];